package mapeamento;
// Generated Sep 18, 2015 3:44:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estudoindividual generated by hbm2java
 */
public class Estudoindividual  implements java.io.Serializable {


     private Integer id;
     private Estudoglobal estudoglobal;
     private String titulo;
     private String descricao;
     private int vp;
     private int fp;
     private int vn;
     private int fn;
     private Set metanaliseestudoindividuals = new HashSet(0);

    public Estudoindividual() {
    }

	
    public Estudoindividual(String titulo, int vp, int fp, int vn, int fn) {
        this.titulo = titulo;
        this.vp = vp;
        this.fp = fp;
        this.vn = vn;
        this.fn = fn;
    }
    public Estudoindividual(Estudoglobal estudoglobal, String titulo, String descricao, int vp, int fp, int vn, int fn, Set metanaliseestudoindividuals) {
       this.estudoglobal = estudoglobal;
       this.titulo = titulo;
       this.descricao = descricao;
       this.vp = vp;
       this.fp = fp;
       this.vn = vn;
       this.fn = fn;
       this.metanaliseestudoindividuals = metanaliseestudoindividuals;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Estudoglobal getEstudoglobal() {
        return this.estudoglobal;
    }
    
    public void setEstudoglobal(Estudoglobal estudoglobal) {
        this.estudoglobal = estudoglobal;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public int getVp() {
        return this.vp;
    }
    
    public void setVp(int vp) {
        this.vp = vp;
    }
    public int getFp() {
        return this.fp;
    }
    
    public void setFp(int fp) {
        this.fp = fp;
    }
    public int getVn() {
        return this.vn;
    }
    
    public void setVn(int vn) {
        this.vn = vn;
    }
    public int getFn() {
        return this.fn;
    }
    
    public void setFn(int fn) {
        this.fn = fn;
    }
    public Set getMetanaliseestudoindividuals() {
        return this.metanaliseestudoindividuals;
    }
    
    public void setMetanaliseestudoindividuals(Set metanaliseestudoindividuals) {
        this.metanaliseestudoindividuals = metanaliseestudoindividuals;
    }




}


