package mapeamento;
// Generated Nov 16, 2015 3:03:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstudoGlobal generated by hbm2java
 */
public class EstudoGlobal  implements java.io.Serializable {


     private Integer id;
     private double lkpositiva;
     private double lknegativa;
     private double erroPadrao;
     private double intervaloConfSup;
     private double intervaloConfInf;
     private Set estudoIndividuals = new HashSet(0);

    public EstudoGlobal() {
    }

	
    public EstudoGlobal(double lkpositiva, double lknegativa, double erroPadrao, double intervaloConfSup, double intervaloConfInf) {
        this.lkpositiva = lkpositiva;
        this.lknegativa = lknegativa;
        this.erroPadrao = erroPadrao;
        this.intervaloConfSup = intervaloConfSup;
        this.intervaloConfInf = intervaloConfInf;
    }
    public EstudoGlobal(double lkpositiva, double lknegativa, double erroPadrao, double intervaloConfSup, double intervaloConfInf, Set estudoIndividuals) {
       this.lkpositiva = lkpositiva;
       this.lknegativa = lknegativa;
       this.erroPadrao = erroPadrao;
       this.intervaloConfSup = intervaloConfSup;
       this.intervaloConfInf = intervaloConfInf;
       this.estudoIndividuals = estudoIndividuals;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public double getLkpositiva() {
        return this.lkpositiva;
    }
    
    public void setLkpositiva(double lkpositiva) {
        this.lkpositiva = lkpositiva;
    }
    public double getLknegativa() {
        return this.lknegativa;
    }
    
    public void setLknegativa(double lknegativa) {
        this.lknegativa = lknegativa;
    }
    public double getErroPadrao() {
        return this.erroPadrao;
    }
    
    public void setErroPadrao(double erroPadrao) {
        this.erroPadrao = erroPadrao;
    }
    public double getIntervaloConfSup() {
        return this.intervaloConfSup;
    }
    
    public void setIntervaloConfSup(double intervaloConfSup) {
        this.intervaloConfSup = intervaloConfSup;
    }
    public double getIntervaloConfInf() {
        return this.intervaloConfInf;
    }
    
    public void setIntervaloConfInf(double intervaloConfInf) {
        this.intervaloConfInf = intervaloConfInf;
    }
    public Set getEstudoIndividuals() {
        return this.estudoIndividuals;
    }
    
    public void setEstudoIndividuals(Set estudoIndividuals) {
        this.estudoIndividuals = estudoIndividuals;
    }




}


