package mapeamento;
// Generated Nov 16, 2015 3:03:25 PM by Hibernate Tools 4.3.1



/**
 * EstudoIndividual generated by hbm2java
 */
public class EstudoIndividual  implements java.io.Serializable {


     private Integer id;
     private EstudoGlobal estudoGlobal;
     private MetanaliseEstudoIndividual metanaliseEstudoIndividual;
     private String titulo;
     private String descricao;
     private int vp;
     private int fp;
     private int vn;
     private int fn;

    public EstudoIndividual() {
    }

    
    public EstudoIndividual(String vp, String fp, String vn, String fn, String descricao, String titulo) {
        this.vp = Integer.parseInt(vp);
        this.fp = Integer.parseInt(fp);
        this.vn = Integer.parseInt(vn);
        this.fn = Integer.parseInt(fn);
        this.descricao = descricao;
        this.titulo = titulo;
    }
	
    public EstudoIndividual(String titulo, int vp, int fp, int vn, int fn) {
        this.titulo = titulo;
        this.vp = vp;
        this.fp = fp;
        this.vn = vn;
        this.fn = fn;
    }
    public EstudoIndividual(EstudoGlobal estudoGlobal, MetanaliseEstudoIndividual metanaliseEstudoIndividual, String titulo, String descricao, int vp, int fp, int vn, int fn) {
       this.estudoGlobal = estudoGlobal;
       this.metanaliseEstudoIndividual = metanaliseEstudoIndividual;
       this.titulo = titulo;
       this.descricao = descricao;
       this.vp = vp;
       this.fp = fp;
       this.vn = vn;
       this.fn = fn;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EstudoGlobal getEstudoGlobal() {
        return this.estudoGlobal;
    }
    
    public void setEstudoGlobal(EstudoGlobal estudoGlobal) {
        this.estudoGlobal = estudoGlobal;
    }
    public MetanaliseEstudoIndividual getMetanaliseEstudoIndividual() {
        return this.metanaliseEstudoIndividual;
    }
    
    public void setMetanaliseEstudoIndividual(MetanaliseEstudoIndividual metanaliseEstudoIndividual) {
        this.metanaliseEstudoIndividual = metanaliseEstudoIndividual;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public int getVp() {
        return this.vp;
    }
    
    public void setVp(int vp) {
        this.vp = vp;
    }
    public int getFp() {
        return this.fp;
    }
    
    public void setFp(int fp) {
        this.fp = fp;
    }
    public int getVn() {
        return this.vn;
    }
    
    public void setVn(int vn) {
        this.vn = vn;
    }
    public int getFn() {
        return this.fn;
    }
    
    public void setFn(int fn) {
        this.fn = fn;
    }




}


