package mapeamento;
// Generated Nov 16, 2015 3:03:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MetanaliseEstudoIndividual generated by hbm2java
 */
public class MetanaliseEstudoIndividual  implements java.io.Serializable {


     private Integer id;
     private double percentualIntervaloConfianca;
     private double sensibilidade;
     private double especificidade;
     private double likelihoodPositiva;
     private double likelihoodNegativa;
     private double erroPadraoLkPositiva;
     private double erroPadraoLkNegativa;
     private double intervaloConfiancaLkpositivaZNegativo;
     private double intervaloConfiancaLkpositivaZPositivo;
     private double intervaloConfiancaLknegativaZNegativo;
     private double intervaloConfiancaLknegativaZPositivo;
     private double pesoMhLkpositiva;
     private double pesoMhLknegativa;
     private Set estudoIndividuals = new HashSet(0);

    public MetanaliseEstudoIndividual() {
    }

	
    public MetanaliseEstudoIndividual(double percentualIntervaloConfianca, double sensibilidade, double especificidade, double likelihoodPositiva, 
                                        double likelihoodNegativa, double erroPadraoLkPositiva, double erroPadraoLkNegativa, double intervaloConfiancaLkpositivaZNegativo, 
                                        double intervaloConfiancaLkpositivaZPositivo, double intervaloConfiancaLknegativaZNegativo, double intervaloConfiancaLknegativaZPositivo, 
                                        double pesoMhLkpositiva, double pesoMhLknegativa) {
        this.percentualIntervaloConfianca = percentualIntervaloConfianca;
        this.sensibilidade = sensibilidade;
        this.especificidade = especificidade;
        this.likelihoodPositiva = likelihoodPositiva;
        this.likelihoodNegativa = likelihoodNegativa;
        this.erroPadraoLkPositiva = erroPadraoLkPositiva;
        this.erroPadraoLkNegativa = erroPadraoLkNegativa;
        this.intervaloConfiancaLkpositivaZNegativo = intervaloConfiancaLkpositivaZNegativo;
        this.intervaloConfiancaLkpositivaZPositivo = intervaloConfiancaLkpositivaZPositivo;
        this.intervaloConfiancaLknegativaZNegativo = intervaloConfiancaLknegativaZNegativo;
        this.intervaloConfiancaLknegativaZPositivo = intervaloConfiancaLknegativaZPositivo;
        this.pesoMhLkpositiva = pesoMhLkpositiva;
        this.pesoMhLknegativa = pesoMhLknegativa;
    }
    public MetanaliseEstudoIndividual(double percentualIntervaloConfianca, double sensibilidade, double especificidade, double likelihoodPositiva, double likelihoodNegativa, 
                                        double erroPadraoLkPositiva, double erroPadraoLkNegativa, double intervaloConfiancaLkpositivaZNegativo, 
                                        double intervaloConfiancaLkpositivaZPositivo, double intervaloConfiancaLknegativaZNegativo, double intervaloConfiancaLknegativaZPositivo, 
                                        double pesoMhLkpositiva, double pesoMhLknegativa, Set estudoIndividuals) {
       this.percentualIntervaloConfianca = percentualIntervaloConfianca;
       this.sensibilidade = sensibilidade;
       this.especificidade = especificidade;
       this.likelihoodPositiva = likelihoodPositiva;
       this.likelihoodNegativa = likelihoodNegativa;
       this.erroPadraoLkPositiva = erroPadraoLkPositiva;
       this.erroPadraoLkNegativa = erroPadraoLkNegativa;
       this.intervaloConfiancaLkpositivaZNegativo = intervaloConfiancaLkpositivaZNegativo;
       this.intervaloConfiancaLkpositivaZPositivo = intervaloConfiancaLkpositivaZPositivo;
       this.intervaloConfiancaLknegativaZNegativo = intervaloConfiancaLknegativaZNegativo;
       this.intervaloConfiancaLknegativaZPositivo = intervaloConfiancaLknegativaZPositivo;
       this.pesoMhLkpositiva = pesoMhLkpositiva;
       this.pesoMhLknegativa = pesoMhLknegativa;
       this.estudoIndividuals = estudoIndividuals;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public double getPercentualIntervaloConfianca() {
        return this.percentualIntervaloConfianca;
    }
    
    public void setPercentualIntervaloConfianca(double percentualIntervaloConfianca) {
        this.percentualIntervaloConfianca = percentualIntervaloConfianca;
    }
    public double getSensibilidade() {
        return this.sensibilidade;
    }
    
    public void setSensibilidade(double sensibilidade) {
        this.sensibilidade = sensibilidade;
    }
    public double getEspecificidade() {
        return this.especificidade;
    }
    
    public void setEspecificidade(double especificidade) {
        this.especificidade = especificidade;
    }
    public double getLikelihoodPositiva() {
        return this.likelihoodPositiva;
    }
    
    public void setLikelihoodPositiva(double likelihoodPositiva) {
        this.likelihoodPositiva = likelihoodPositiva;
    }
    public double getLikelihoodNegativa() {
        return this.likelihoodNegativa;
    }
    
    public void setLikelihoodNegativa(double likelihoodNegativa) {
        this.likelihoodNegativa = likelihoodNegativa;
    }
    public double getErroPadraoLkPositiva() {
        return this.erroPadraoLkPositiva;
    }
    
    public void setErroPadraoLkPositiva(double erroPadraoLkPositiva) {
        this.erroPadraoLkPositiva = erroPadraoLkPositiva;
    }
    public double getErroPadraoLkNegativa() {
        return this.erroPadraoLkNegativa;
    }
    
    public void setErroPadraoLkNegativa(double erroPadraoLkNegativa) {
        this.erroPadraoLkNegativa = erroPadraoLkNegativa;
    }
    public double getIntervaloConfiancaLkpositivaZNegativo() {
        return this.intervaloConfiancaLkpositivaZNegativo;
    }
    
    public void setIntervaloConfiancaLkpositivaZNegativo(double intervaloConfiancaLkpositivaZNegativo) {
        this.intervaloConfiancaLkpositivaZNegativo = intervaloConfiancaLkpositivaZNegativo;
    }
    public double getIntervaloConfiancaLkpositivaZPositivo() {
        return this.intervaloConfiancaLkpositivaZPositivo;
    }
    
    public void setIntervaloConfiancaLkpositivaZPositivo(double intervaloConfiancaLkpositivaZPositivo) {
        this.intervaloConfiancaLkpositivaZPositivo = intervaloConfiancaLkpositivaZPositivo;
    }
    public double getIntervaloConfiancaLknegativaZNegativo() {
        return this.intervaloConfiancaLknegativaZNegativo;
    }
    
    public void setIntervaloConfiancaLknegativaZNegativo(double intervaloConfiancaLknegativaZNegativo) {
        this.intervaloConfiancaLknegativaZNegativo = intervaloConfiancaLknegativaZNegativo;
    }
    public double getIntervaloConfiancaLknegativaZPositivo() {
        return this.intervaloConfiancaLknegativaZPositivo;
    }
    
    public void setIntervaloConfiancaLknegativaZPositivo(double intervaloConfiancaLknegativaZPositivo) {
        this.intervaloConfiancaLknegativaZPositivo = intervaloConfiancaLknegativaZPositivo;
    }
    public double getPesoMhLkpositiva() {
        return this.pesoMhLkpositiva;
    }
    
    public void setPesoMhLkpositiva(double pesoMhLkpositiva) {
        this.pesoMhLkpositiva = pesoMhLkpositiva;
    }
    public double getPesoMhLknegativa() {
        return this.pesoMhLknegativa;
    }
    
    public void setPesoMhLknegativa(double pesoMhLknegativa) {
        this.pesoMhLknegativa = pesoMhLknegativa;
    }
    public Set getEstudoIndividuals() {
        return this.estudoIndividuals;
    }
    
    public void setEstudoIndividuals(Set estudoIndividuals) {
        this.estudoIndividuals = estudoIndividuals;
    }




}


