/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import javax.swing.JOptionPane;
import mapeamento.ModuloLikelihood;
import moduloLikelihoodException.ModuloLikelihoodException;

/**
 *
 * @author allan
 */
public class TelaHome extends javax.swing.JFrame {

    private int intervaloDeConfianca;
    
    /**
     * Creates new form TelaHome
     */
    public TelaHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IntervaloDeConfianca_label = new javax.swing.JLabel();
        IntervaloDeConfianca_text = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        EstudoMenu = new javax.swing.JMenu();
        EstudoCadastrar = new javax.swing.JMenuItem();
        EstudoConsultar = new javax.swing.JMenuItem();
        EstudoExcluir = new javax.swing.JMenuItem();
        AgruparMenu = new javax.swing.JMenu();
        BasesMenu = new javax.swing.JMenu();
        BasesImportar = new javax.swing.JMenuItem();
        BasesExportar = new javax.swing.JMenuItem();
        AjudaMenu = new javax.swing.JMenu();
        DocumentacaoAjuda = new javax.swing.JMenuItem();
        WikiAjuda = new javax.swing.JMenuItem();
        SobreAjuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SHELL PEARSON | Módulo Likelihood ");
        setName("TelaHome"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        IntervaloDeConfianca_label.setText("Intervalo de Confiança");

        IntervaloDeConfianca_text.setForeground(new java.awt.Color(153, 153, 153));
        IntervaloDeConfianca_text.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        IntervaloDeConfianca_text.setText("95");
        IntervaloDeConfianca_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IntervaloDeConfianca_textKeyTyped(evt);
            }
        });

        jLabel1.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IntervaloDeConfianca_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(IntervaloDeConfianca_text, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IntervaloDeConfianca_label)
                    .addComponent(IntervaloDeConfianca_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(285, Short.MAX_VALUE))
        );

        EstudoMenu.setText("Estudo");

        EstudoCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        EstudoCadastrar.setText("Cadastrar");
        EstudoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudoCadastrarActionPerformed(evt);
            }
        });
        EstudoMenu.add(EstudoCadastrar);

        EstudoConsultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        EstudoConsultar.setText("Consultar");
        EstudoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudoConsultarActionPerformed(evt);
            }
        });
        EstudoMenu.add(EstudoConsultar);

        EstudoExcluir.setText("Excluir");
        EstudoMenu.add(EstudoExcluir);

        jMenuBar1.add(EstudoMenu);

        AgruparMenu.setText("Agrupar");
        jMenuBar1.add(AgruparMenu);

        BasesMenu.setText("Bases");

        BasesImportar.setText("Importar");
        BasesMenu.add(BasesImportar);

        BasesExportar.setText("Exportar");
        BasesMenu.add(BasesExportar);

        jMenuBar1.add(BasesMenu);

        AjudaMenu.setText("Ajuda");

        DocumentacaoAjuda.setText("Documentação");
        AjudaMenu.add(DocumentacaoAjuda);

        WikiAjuda.setText("Wiki");
        AjudaMenu.add(WikiAjuda);

        SobreAjuda.setText("Sobre");
        AjudaMenu.add(SobreAjuda);

        jMenuBar1.add(AjudaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(485, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EstudoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudoCadastrarActionPerformed
        
        try{
            this.intervaloDeConfianca = Integer.parseInt(IntervaloDeConfianca_text.getText()); 
            new TelaEstudoIndividual("Cadastrar", this.intervaloDeConfianca).setVisible(true);
        }
        catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this.rootPane, "Antes de cadastrar um novo estudo, por favor forneça um valor válido para o intervalo de confiança");
        }
    }//GEN-LAST:event_EstudoCadastrarActionPerformed

    private void EstudoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudoConsultarActionPerformed
        new TelaEstudoIndividual("Consultar", this.intervaloDeConfianca).setVisible(true);
    }//GEN-LAST:event_EstudoConsultarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ModuloLikelihood.fechaSessaoHibernate();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.IntervaloDeConfianca_text.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void IntervaloDeConfianca_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IntervaloDeConfianca_textKeyTyped
        this.IntervaloDeConfianca_text.setForeground(Color.BLACK);
    }//GEN-LAST:event_IntervaloDeConfianca_textKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHome().setVisible(true);
            }
        });
    }
    
    public int getIntervaloDeConfianca() {
        return intervaloDeConfianca;
    }

    public void setIntervaloDeConfianca(int intervaloDeConfianca) {
        this.intervaloDeConfianca = intervaloDeConfianca;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AgruparMenu;
    private javax.swing.JMenu AjudaMenu;
    private javax.swing.JMenuItem BasesExportar;
    private javax.swing.JMenuItem BasesImportar;
    private javax.swing.JMenu BasesMenu;
    private javax.swing.JMenuItem DocumentacaoAjuda;
    private javax.swing.JMenuItem EstudoCadastrar;
    private javax.swing.JMenuItem EstudoConsultar;
    private javax.swing.JMenuItem EstudoExcluir;
    private javax.swing.JMenu EstudoMenu;
    private javax.swing.JLabel IntervaloDeConfianca_label;
    private javax.swing.JTextField IntervaloDeConfianca_text;
    private javax.swing.JMenuItem SobreAjuda;
    private javax.swing.JMenuItem WikiAjuda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
