/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import mapeamento.ModuloLikelihood;

/**
 *
 * @author allan
 */
public class TelaHome extends javax.swing.JFrame {

    /**
     * Creates new form TelaHome
     */
    public TelaHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        EstudoMenu = new javax.swing.JMenu();
        EstudoCadastrar = new javax.swing.JMenuItem();
        EstudoConsultar = new javax.swing.JMenuItem();
        EstudoExcluir = new javax.swing.JMenuItem();
        AgruparMenu = new javax.swing.JMenu();
        BasesMenu = new javax.swing.JMenu();
        BasesImportar = new javax.swing.JMenuItem();
        BasesExportar = new javax.swing.JMenuItem();
        AjudaMenu = new javax.swing.JMenu();
        DocumentacaoAjuda = new javax.swing.JMenuItem();
        WikiAjuda = new javax.swing.JMenuItem();
        SobreAjuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SHELL PEARSON | Módulo Likelihood ");
        setName("TelaHome"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        EstudoMenu.setText("Estudo");

        EstudoCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        EstudoCadastrar.setText("Cadastrar");
        EstudoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudoCadastrarActionPerformed(evt);
            }
        });
        EstudoMenu.add(EstudoCadastrar);

        EstudoConsultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        EstudoConsultar.setText("Consultar");
        EstudoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudoConsultarActionPerformed(evt);
            }
        });
        EstudoMenu.add(EstudoConsultar);

        EstudoExcluir.setText("Excluir");
        EstudoMenu.add(EstudoExcluir);

        jMenuBar1.add(EstudoMenu);

        AgruparMenu.setText("Agrupar");
        jMenuBar1.add(AgruparMenu);

        BasesMenu.setText("Bases");

        BasesImportar.setText("Importar");
        BasesMenu.add(BasesImportar);

        BasesExportar.setText("Exportar");
        BasesMenu.add(BasesExportar);

        jMenuBar1.add(BasesMenu);

        AjudaMenu.setText("Ajuda");

        DocumentacaoAjuda.setText("Documentação");
        AjudaMenu.add(DocumentacaoAjuda);

        WikiAjuda.setText("Wiki");
        AjudaMenu.add(WikiAjuda);

        SobreAjuda.setText("Sobre");
        AjudaMenu.add(SobreAjuda);

        jMenuBar1.add(AjudaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EstudoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudoCadastrarActionPerformed
        new TelaEstudoIndividual("Cadastrar").setVisible(true);
    }//GEN-LAST:event_EstudoCadastrarActionPerformed

    private void EstudoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudoConsultarActionPerformed
        new TelaEstudoIndividual("Consultar").setVisible(true);
    }//GEN-LAST:event_EstudoConsultarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ModuloLikelihood.fechaSessaoHibernate();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AgruparMenu;
    private javax.swing.JMenu AjudaMenu;
    private javax.swing.JMenuItem BasesExportar;
    private javax.swing.JMenuItem BasesImportar;
    private javax.swing.JMenu BasesMenu;
    private javax.swing.JMenuItem DocumentacaoAjuda;
    private javax.swing.JMenuItem EstudoCadastrar;
    private javax.swing.JMenuItem EstudoConsultar;
    private javax.swing.JMenuItem EstudoExcluir;
    private javax.swing.JMenu EstudoMenu;
    private javax.swing.JMenuItem SobreAjuda;
    private javax.swing.JMenuItem WikiAjuda;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
