/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import estatistica.Agrupados;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mapeamento.EstudoGlobal;
import mapeamento.EstudoIndividual;
import moduloLikelihoodException.ModuloLikelihoodException;

/**
 *
 * @author allan
 */
public class TelaListagemEstudosIndividuais extends javax.swing.JFrame {

    private Vector<String> tableHeaders = new Vector<String>();
    private Vector<Object> oneRow = null, row = null;
    private Vector tableData = new Vector();
    private ArrayList <EstudoIndividual> listaEstInd = null;
    private ArrayList <EstudoGlobal> listaEstGlob = null;
    private EstudoIndividual estInd = null;
    
    /**
     * Creates new form TelaListagemEstudosIndividuais
     */
    public TelaListagemEstudosIndividuais() {
        inicializaTela();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listagemEstInd_tabela = new javax.swing.JTable();
        listagemEstInd_deletar_button = new javax.swing.JButton();
        listagemEstInd_alterarDados_button = new javax.swing.JButton();
        listagemEstInd_removerEstGlob_button = new javax.swing.JButton();
        listagemEstInd_abrirMet_button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listagem Estudos Individuais");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Estudos Individuais", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        listagemEstInd_tabela.setModel(new javax.swing.table.DefaultTableModel(tableData, tableHeaders){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        }
    );
    listagemEstInd_tabela.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
    listagemEstInd_tabela.setShowHorizontalLines(false);
    listagemEstInd_tabela.setShowVerticalLines(false);
    listagemEstInd_tabela.getTableHeader().setReorderingAllowed(false);
    this.listagemEstInd_tabela.getColumnModel().getColumn(7).setPreferredWidth(130);
    this.listagemEstInd_tabela.setSelectionMode(NORMAL);
    jScrollPane1.setViewportView(listagemEstInd_tabela);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    listagemEstInd_deletar_button.setText("Deletar");
    listagemEstInd_deletar_button.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            listagemEstInd_deletar_buttonActionPerformed(evt);
        }
    });

    listagemEstInd_alterarDados_button.setText("Alterar dados");
    listagemEstInd_alterarDados_button.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            listagemEstInd_alterarDados_buttonActionPerformed(evt);
        }
    });

    listagemEstInd_removerEstGlob_button.setText("Remover de Estudo Global");
    listagemEstInd_removerEstGlob_button.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            listagemEstInd_removerEstGlob_buttonActionPerformed(evt);
        }
    });

    listagemEstInd_abrirMet_button.setText("Abrir Metanálise");
    listagemEstInd_abrirMet_button.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            listagemEstInd_abrirMet_buttonActionPerformed(evt);
        }
    });

    jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

    jSeparator2.setForeground(new java.awt.Color(204, 204, 204));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(42, 42, 42)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(listagemEstInd_removerEstGlob_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listagemEstInd_alterarDados_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listagemEstInd_abrirMet_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listagemEstInd_deletar_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1)
                .addComponent(jSeparator2))
            .addContainerGap(60, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createSequentialGroup()
                    .addGap(98, 98, 98)
                    .addComponent(listagemEstInd_abrirMet_button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(listagemEstInd_alterarDados_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)
                    .addComponent(listagemEstInd_removerEstGlob_button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(listagemEstInd_deletar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listagemEstInd_abrirMet_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listagemEstInd_abrirMet_buttonActionPerformed
       if(this.listagemEstInd_tabela.getSelectedRow() >= 0){
           new gui.TelaMetanaliseEstudoIndividual(this.listagemEstInd_tabela.getSelectedRow()).setVisible(true);
       }
    }//GEN-LAST:event_listagemEstInd_abrirMet_buttonActionPerformed

    private void listagemEstInd_alterarDados_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listagemEstInd_alterarDados_buttonActionPerformed
        if(this.listagemEstInd_tabela.getSelectedRow()>=0){
            try {
                    this.listaEstInd = persistencia.CRUD.executaConsulta(String.valueOf(this.listagemEstInd_tabela.getValueAt(this.listagemEstInd_tabela.getSelectedRow(), 0)), null);
                    if(this.listaEstInd.get(0).getEstudoGlobal() != null){
                        if(JOptionPane.YES_OPTION == (JOptionPane.showConfirmDialog(this.rootPane, "A alteração deste estudo alterará o valor do estudo global do qual faz parte. Deseja prosseguir?", "Confirmação de alteração", JOptionPane.INFORMATION_MESSAGE))){
                            new gui.TelaEstudoIndividual(this.listaEstInd, true).setVisible(true);    
                        }
                    }else{
                        new gui.TelaEstudoIndividual(this.listaEstInd).setVisible(true);    
                    }
            } catch (ModuloLikelihoodException ex) {
                    JOptionPane.showMessageDialog(this.rootPane, ex.getMessage());
            }
        }
    }//GEN-LAST:event_listagemEstInd_alterarDados_buttonActionPerformed

    private void listagemEstInd_removerEstGlob_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listagemEstInd_removerEstGlob_buttonActionPerformed
        if(this.listagemEstInd_tabela.getSelectedRow()>-1){
            if(!(this.listagemEstInd_tabela.getValueAt(this.listagemEstInd_tabela.getSelectedRow(), 7).toString()).equals("-")){
                try {
                    this.estInd = (EstudoIndividual) persistencia.CRUD.executaConsulta(this.listagemEstInd_tabela.getValueAt(this.listagemEstInd_tabela.getSelectedRow(), 0).toString(), null).get(0);
                    if(this.estInd.getEstudoGlobal() != null){                        
                        this.listaEstInd = (ArrayList<EstudoIndividual>) persistencia.CRUD.executaConsulta(Integer.parseInt(this.listagemEstInd_tabela.getValueAt(this.listagemEstInd_tabela.getSelectedRow(), 7).toString()));                   
                        this.listaEstInd.remove(this.estInd);
                        
                        EstudoGlobal aux = this.estInd.getEstudoGlobal();
                        
                        this.estInd.setEstudoGlobal(null);
                        persistencia.CRUD.executaAtualizacao(this.estInd);
                        
                        Agrupados.resetaValores();
                        
                        if(this.listaEstInd.size()>0){
                            Agrupados.setEstudosIndividuais(this.listaEstInd);
                            Agrupados.calculaLikelihoodGlobal();
                       
                            this.listaEstGlob = (ArrayList<EstudoGlobal>) persistencia.CRUD.executaConsulta(true);

                            for(EstudoGlobal estGlob : this.listaEstGlob){
                                if(estGlob.getId() == (Integer.parseInt(this.listagemEstInd_tabela.getValueAt(this.listagemEstInd_tabela.getSelectedRow(), 7).toString()))){
                                    estGlob.setLkpositiva(Agrupados.getLKPositiva());
                                    estGlob.setLknegativa(Agrupados.getLKNegativa());
                                    persistencia.CRUD.executaAtualizacao(estGlob);
                                    break;
                                }
                            }
                        }else{
                            persistencia.CRUD.executaExclusao(aux);
                        }
                        
                        this.listagemEstInd_tabela.setValueAt("-", this.listagemEstInd_tabela.getSelectedRow(), 7);
                        JOptionPane.showMessageDialog(this.rootPane, "Estudo global removido com sucesso", "Confirmação de alteração", JOptionPane.INFORMATION_MESSAGE);
                    } else{
                        this.listagemEstInd_tabela.getModel().setValueAt("-", this.listagemEstInd_tabela.getSelectedRow(), 7);
                        throw new ModuloLikelihoodException("Ocorreu um erro ao remover o estudo individual "+estInd.getId()+" do estudo global.");                        
                    }
                } catch (ModuloLikelihoodException ex) {
                    JOptionPane.showMessageDialog(this.rootPane, ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_listagemEstInd_removerEstGlob_buttonActionPerformed

    private void listagemEstInd_deletar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listagemEstInd_deletar_buttonActionPerformed
        if(this.listagemEstInd_tabela.getSelectedRow()>-1){
            if(JOptionPane.YES_OPTION == (JOptionPane.showConfirmDialog(this.rootPane, "Tem certeza que deseja excluir o estudo " +
                                                                        (this.listagemEstInd_tabela.getValueAt(this.listagemEstInd_tabela.getSelectedRow(), 0).toString())
                                                                        +" ?" , "Confirmação de exclusão", JOptionPane.WARNING_MESSAGE))){
                if((this.listagemEstInd_tabela.getValueAt(this.listagemEstInd_tabela.getSelectedRow(), 7).toString().equals("-"))){
                    try {
                        persistencia.CRUD.executaExclusao((EstudoIndividual)(persistencia.CRUD.executaConsulta(this.listagemEstInd_tabela.getValueAt(this.listagemEstInd_tabela.getSelectedRow(), 0).toString(), null).get(0)));
                    } catch (ModuloLikelihoodException ex) {
                        JOptionPane.showMessageDialog(this.rootPane, ex.getMessage());
                    }
                    DefaultTableModel modeloTabela = (DefaultTableModel) this.listagemEstInd_tabela.getModel();
                    modeloTabela.removeRow(this.listagemEstInd_tabela.getSelectedRow());
                } else{
                    JOptionPane.showMessageDialog(this.rootPane, "Não é possível excluir o estudo individual, é necessário removê-lo do respectivo estudo global.", "Erro na exclusão do estudo individual", JOptionPane.ERROR_MESSAGE);
                }
            }
       }else{
            this.listagemEstInd_tabela.changeSelection(0, 0, true, false);
        }
    }//GEN-LAST:event_listagemEstInd_deletar_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListagemEstudosIndividuais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListagemEstudosIndividuais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListagemEstudosIndividuais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListagemEstudosIndividuais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListagemEstudosIndividuais().setVisible(true);
            }
        });
    }

    private void inicializaTela(){
        this.tableHeaders.add("ID"); 
        this.tableHeaders.add("Título");
        this.tableHeaders.add("Descrição");
        this.tableHeaders.add("VP");
        this.tableHeaders.add("FP");
        this.tableHeaders.add("VN");
        this.tableHeaders.add("FN");
        this.tableHeaders.add("Estudo Global");
        
        for(Object obj : persistencia.CRUD.executaConsulta()){
            this.estInd = (EstudoIndividual) obj;
            this.oneRow = new Vector<Object>();
            this.oneRow.add(estInd.getId());
            this.oneRow.add(estInd.getTitulo());
            this.oneRow.add(estInd.getDescricao());
            this.oneRow.add(estInd.getVp());
            this.oneRow.add(estInd.getFp());
            this.oneRow.add(estInd.getVn());
            this.oneRow.add(estInd.getFn());
            if(estInd.getEstudoGlobal()!=null){
                this.oneRow.add(estInd.getEstudoGlobal().getId());
            }else{
                this.oneRow.add("-");
            }
            tableData.add(oneRow);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton listagemEstInd_abrirMet_button;
    private javax.swing.JButton listagemEstInd_alterarDados_button;
    private javax.swing.JButton listagemEstInd_deletar_button;
    private javax.swing.JButton listagemEstInd_removerEstGlob_button;
    private javax.swing.JTable listagemEstInd_tabela;
    // End of variables declaration//GEN-END:variables
}
