/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import estatistica.Agrupados;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import mapeamento.EstudoIndividual;
import estatistica.Metanalise;
import java.awt.Color;
import mapeamento.MetanaliseEstudoIndividual;
import moduloLikelihoodException.ModuloLikelihoodException;

/**
 *
 * @author allan
 */
public class TelaEstudoIndividual extends javax.swing.JFrame {

    private double percentualIntervaloDeConfianca;
    private EstudoIndividual estInd = null;
    private ArrayList<EstudoIndividual> resultadosConsulta = null;
    private MetanaliseEstudoIndividual metanalise_estInd = null;

    /**
     * Creates new form TelaEstudoIndividual
     * @param textoBotao
     */
    public TelaEstudoIndividual(String textoBotao, double percentualIntervaloDeConfianca) throws ModuloLikelihoodException{
        this.confereIntervaloDeConfianca(percentualIntervaloDeConfianca);
        initComponents();
        this.EstudoButton_button.setText(textoBotao);
        if(textoBotao.equals("Consultar")){
            this.atualizaDados_Tela(textoBotao);
        }
    }
    
    public TelaEstudoIndividual(ArrayList<EstudoIndividual> listaEstInd){
        initComponents();
        this.atualizaDados_Tela(listaEstInd);
    }
    
    public TelaEstudoIndividual(ArrayList<EstudoIndividual> listaEstInd, boolean vinculadoEstudoGlobal){
        initComponents();
        this.atualizaDados_Tela(listaEstInd);
    }
    
    public TelaEstudoIndividual(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EstudoTabela_table1 = new javax.swing.JTable();
        EstudoDesc_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EstudoDesc_textarea = new javax.swing.JTextArea();
        EstudoTitulo_label = new javax.swing.JLabel();
        EstudoTitulo_text = new javax.swing.JTextField();
        EstudoButton_button = new javax.swing.JButton();
        EstudoID_label = new javax.swing.JLabel();
        EstudoID_text = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        EstudoTabela_label1 = new javax.swing.JLabel();
        EstudoTabela_label2 = new javax.swing.JLabel();
        EstudoTabela_label3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        EstudoTabela_label4 = new javax.swing.JLabel();
        EstudoTabela_label5 = new javax.swing.JLabel();
        EstudoTabela_label6 = new javax.swing.JLabel();
        EstudoTabela_VPtext = new javax.swing.JTextField();
        EstudoTabela_FPtext = new javax.swing.JTextField();
        EstudoTabela_FNtext = new javax.swing.JTextField();
        EstudoTabela_VNtext = new javax.swing.JTextField();
        EstudoTabela_TotalP = new javax.swing.JTextField();
        EstudoTabela_TotalN = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        EstudoTabela_label7 = new javax.swing.JLabel();
        EstudoTabela_TotalD = new javax.swing.JTextField();
        EstudoTabela_TotalND = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        EstudoTabela_TotalND1 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        EstudoTabela_label8 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();

        EstudoTabela_table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Positivo", null, null, null},
                {"Negativo", null, null, null},
                {"Total", null, null, null}
            },
            new String [] {
                "Teste Experimental", "Com doença", "Sem doença", "Total"
            }
        ));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estudo Individual");
        setName("TelaEstudoIndividual"); // NOI18N
        setResizable(false);

        EstudoDesc_label.setText("Descrição");

        EstudoDesc_textarea.setColumns(20);
        EstudoDesc_textarea.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        EstudoDesc_textarea.setRows(5);
        jScrollPane1.setViewportView(EstudoDesc_textarea);

        EstudoTitulo_label.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        EstudoTitulo_label.setLabelFor(EstudoTitulo_text);
        EstudoTitulo_label.setText("Título");

        EstudoButton_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudoButton_buttonActionPerformed(evt);
            }
        });

        EstudoID_label.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        EstudoID_label.setText("ID");

        EstudoID_text.setEditable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tabela 2x2 ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        EstudoTabela_label1.setText("Teste Experimental");

        EstudoTabela_label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EstudoTabela_label2.setText("Positivo");
        EstudoTabela_label2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        EstudoTabela_label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EstudoTabela_label3.setText("Negativo");
        EstudoTabela_label3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        EstudoTabela_label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EstudoTabela_label4.setText("Com doença");
        EstudoTabela_label4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        EstudoTabela_label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EstudoTabela_label5.setText("Sem doença");
        EstudoTabela_label5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        EstudoTabela_label6.setText("Total");

        EstudoTabela_VPtext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EstudoTabela_VPtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EstudoTabela_VPtextFocusLost(evt);
            }
        });

        EstudoTabela_FPtext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EstudoTabela_FPtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EstudoTabela_FPtextFocusLost(evt);
            }
        });

        EstudoTabela_FNtext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EstudoTabela_FNtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EstudoTabela_FNtextFocusLost(evt);
            }
        });

        EstudoTabela_VNtext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EstudoTabela_VNtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EstudoTabela_VNtextFocusLost(evt);
            }
        });

        EstudoTabela_TotalP.setEditable(false);
        EstudoTabela_TotalP.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        EstudoTabela_TotalN.setEditable(false);
        EstudoTabela_TotalN.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        EstudoTabela_label7.setText("Total");

        EstudoTabela_TotalD.setEditable(false);
        EstudoTabela_TotalD.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        EstudoTabela_TotalND.setEditable(false);
        EstudoTabela_TotalND.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        EstudoTabela_TotalND1.setEditable(false);
        EstudoTabela_TotalND1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        EstudoTabela_label8.setText("Teste de referência");

        jSeparator8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jSeparator9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jSeparator10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jSeparator5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jSeparator11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(EstudoTabela_label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EstudoTabela_label4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EstudoTabela_label6)
                        .addGap(125, 125, 125))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(EstudoTabela_label7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EstudoTabela_TotalD, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator10)
                                    .addComponent(EstudoTabela_label2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(EstudoTabela_label3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator1)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(EstudoTabela_VPtext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(EstudoTabela_FNtext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jSeparator4)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 10, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(EstudoTabela_label5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jSeparator5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(EstudoTabela_TotalND, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EstudoTabela_FPtext, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EstudoTabela_VNtext, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator11)
                            .addComponent(jSeparator9)
                            .addComponent(EstudoTabela_TotalND1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EstudoTabela_TotalN, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EstudoTabela_TotalP, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EstudoTabela_label8)
                .addGap(267, 267, 267))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EstudoTabela_label8)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EstudoTabela_label4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EstudoTabela_label5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(EstudoTabela_label1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(EstudoTabela_label6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EstudoTabela_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EstudoTabela_VPtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EstudoTabela_label3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EstudoTabela_FNtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(EstudoTabela_label7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(EstudoTabela_TotalP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(EstudoTabela_TotalN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(EstudoTabela_FPtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(EstudoTabela_VNtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(9, 9, 9))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSeparator10)
                                            .addComponent(jSeparator5)
                                            .addComponent(jSeparator4))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EstudoTabela_TotalD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EstudoTabela_TotalND1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EstudoTabela_TotalND, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator2))
                        .addGap(66, 66, 66))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EstudoDesc_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EstudoID_label))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EstudoTitulo_label)
                                .addGap(18, 18, 18)
                                .addComponent(EstudoTitulo_text, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EstudoButton_button, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(EstudoID_text))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EstudoTitulo_label)
                        .addComponent(EstudoTitulo_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(EstudoButton_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EstudoDesc_label)
                    .addComponent(EstudoID_label)
                    .addComponent(EstudoID_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EstudoButton_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudoButton_buttonActionPerformed
        if(this.EstudoButton_button.getText().equals("Cadastrar")){
            int id = 0;
            try {
               this.estInd = new EstudoIndividual(this.EstudoTabela_VPtext.getText(), this.EstudoTabela_FPtext.getText(), 
                                                                this.EstudoTabela_VNtext.getText(), this.EstudoTabela_FNtext.getText(), 
                                                                this.EstudoDesc_textarea.getText(), this.EstudoTitulo_text.getText());
                persistencia.CRUD.executaCadastro(this.estInd);
                JOptionPane.showMessageDialog(this.rootPane, "Cadastro do estudo individual "+this.estInd.getId()+" efetuado com sucesso!");
                this.atualizaDados_Tela();
                
                Metanalise.resetaValores();
                this.metanalise_estInd = this.efetuaMetanalise(this.estInd);
                persistencia.CRUD.executaCadastro(this.metanalise_estInd);
                
                this.estInd.setMetanaliseEstudoIndividual(this.metanalise_estInd);
                
                persistencia.CRUD.executaAtualizacao(this.estInd);
                
                new gui.TelaMetanaliseEstudoIndividual().setVisible(true);
            } catch (ModuloLikelihoodException ex) {
                JOptionPane.showMessageDialog(this.rootPane, ex.getMessage());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this.rootPane, "O cadastro do Estudo Individual falhou. Verifique os valores fornecidos (título e tabela 2x2)");
            }
        } else {
            if(this.EstudoButton_button.getText().equals("Consultar")){
                 try {
                    resultadosConsulta = persistencia.CRUD.executaConsulta(EstudoID_text.getText(), EstudoTitulo_text.getText());
                    if(!resultadosConsulta.equals(null) && resultadosConsulta.size() > 0){
                    this.atualizaDados_Tela(resultadosConsulta);
                    } else{
                        JOptionPane.showMessageDialog(this.rootPane, "Nenhum estudo individual encontrado");
                    }
                } catch (ModuloLikelihoodException ex) {
                    JOptionPane.showMessageDialog(this.rootPane, ex.getMessage());
                }
            } else{ //Alterar
                this.estInd.setTitulo(this.EstudoTitulo_text.getText());
                this.estInd.setDescricao(this.EstudoDesc_textarea.getText());
                this.estInd.setVp(Integer.parseInt(this.EstudoTabela_VPtext.getText()));
                this.estInd.setFp(Integer.parseInt(this.EstudoTabela_FPtext.getText()));
                this.estInd.setVn(Integer.parseInt(this.EstudoTabela_VNtext.getText()));
                this.estInd.setFn(Integer.parseInt(this.EstudoTabela_FNtext.getText()));
                
                persistencia.CRUD.executaAtualizacao(estInd);
                this.atualizaDados_Tela();
                if(this.estInd.getEstudoGlobal() != null){
                    this.resultadosConsulta = (ArrayList<EstudoIndividual>) persistencia.CRUD.executaConsulta(this.estInd.getEstudoGlobal().getId());
                    Agrupados.resetaValores();
                    Agrupados.setEstudosIndividuais(this.resultadosConsulta);
                    Agrupados.calculaLikelihoodGlobal();
                    this.estInd.getEstudoGlobal().setLkpositiva(Agrupados.getLKPositiva());
                    this.estInd.getEstudoGlobal().setLknegativa(Agrupados.getLKNegativa());
                    persistencia.CRUD.executaAtualizacao(this.estInd.getEstudoGlobal());
                }
                this.estInd = null;
                
                JOptionPane.showMessageDialog(this.rootPane, "Alteração efetuada com sucesso!");
                this.dispose();
            }
           
        }
    }//GEN-LAST:event_EstudoButton_buttonActionPerformed

    private void EstudoTabela_VPtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EstudoTabela_VPtextFocusLost
        int totalHorizontal = 0, totalVertical = 0, totalND1 = 0;
        if(!EstudoTabela_VPtext.getText().equals("")){
           try{
            if(!(EstudoTabela_FPtext.getText().equals(""))){
                totalHorizontal = Integer.parseInt(this.EstudoTabela_VPtext.getText()) + Integer.parseInt(this.EstudoTabela_FPtext.getText());
            } else {
                totalHorizontal = Integer.parseInt(this.EstudoTabela_VPtext.getText());
            }
            
            if(!(EstudoTabela_FNtext.getText().equals(""))){
                totalVertical = Integer.parseInt(this.EstudoTabela_VPtext.getText()) + Integer.parseInt(this.EstudoTabela_FNtext.getText());
            }else{
                totalVertical = Integer.parseInt(this.EstudoTabela_VPtext.getText());
            }
            this.EstudoTabela_TotalP.setText(String.valueOf(totalHorizontal));
            this.EstudoTabela_TotalD.setText(String.valueOf(totalVertical));
            
            if(!(this.EstudoTabela_TotalN.getText().equals(""))){
                totalND1 = totalHorizontal + Integer.parseInt(this.EstudoTabela_TotalN.getText());
                this.EstudoTabela_TotalND1.setText(String.valueOf(totalND1));
            }else{
                    this.EstudoTabela_TotalND1.setText(String.valueOf(totalHorizontal));
            }
            } catch (NumberFormatException ex)   {
                JOptionPane.showMessageDialog(this.rootPane, "Por favor, insira um valor válido.");
                this.EstudoTabela_VPtext.setText("");
            } 
        }
    }//GEN-LAST:event_EstudoTabela_VPtextFocusLost

    private void EstudoTabela_FPtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EstudoTabela_FPtextFocusLost
        int totalHorizontal = 0, totalVertical = 0, totalND1 = 0;
        if(!EstudoTabela_FPtext.getText().equals("")){
            try{
                if(!(EstudoTabela_VPtext.getText().equals(""))){
                    totalHorizontal = Integer.parseInt(this.EstudoTabela_FPtext.getText()) + Integer.parseInt(this.EstudoTabela_VPtext.getText());
                } else {
                    totalHorizontal = Integer.parseInt(this.EstudoTabela_FPtext.getText());
                } 

                if(!(EstudoTabela_VNtext.getText().equals(""))){
                    totalVertical = Integer.parseInt(this.EstudoTabela_FPtext.getText()) + Integer.parseInt(this.EstudoTabela_VNtext.getText());
                }else{
                    totalVertical = Integer.parseInt(this.EstudoTabela_FPtext.getText());
                }
                this.EstudoTabela_TotalP.setText(String.valueOf(totalHorizontal));
                this.EstudoTabela_TotalND.setText(String.valueOf(totalVertical));
                
                if(!(this.EstudoTabela_TotalN.getText().equals(""))){
                    totalND1 = totalHorizontal + Integer.parseInt(this.EstudoTabela_TotalN.getText());
                    this.EstudoTabela_TotalND1.setText(String.valueOf(totalND1));
                }else{
                    this.EstudoTabela_TotalND1.setText(String.valueOf(totalHorizontal));
                }
            } catch (NumberFormatException ex)   {
                JOptionPane.showMessageDialog(this.rootPane, "Por favor, insira um valor válido.");
                this.EstudoTabela_FPtext.setText("");
            }
        }
    }//GEN-LAST:event_EstudoTabela_FPtextFocusLost

    private void EstudoTabela_FNtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EstudoTabela_FNtextFocusLost
        int totalHorizontal = 0, totalVertical = 0, totalND1 = 0;
        if(!EstudoTabela_FNtext.getText().equals("")){
            try{
                if(!(EstudoTabela_VNtext.getText().equals(""))){
                    totalHorizontal = Integer.parseInt(this.EstudoTabela_FNtext.getText()) + Integer.parseInt(this.EstudoTabela_VNtext.getText());
                } else {
                    totalHorizontal = Integer.parseInt(this.EstudoTabela_FNtext.getText());
                }

                if(!(EstudoTabela_VPtext.getText().equals(""))){
                    totalVertical = Integer.parseInt(this.EstudoTabela_FNtext.getText()) + Integer.parseInt(this.EstudoTabela_VPtext.getText());
                }else{
                    totalVertical = Integer.parseInt(this.EstudoTabela_FNtext.getText());
                }
                this.EstudoTabela_TotalN.setText(String.valueOf(totalHorizontal));
                this.EstudoTabela_TotalD.setText(String.valueOf(totalVertical));
                
                if(!(this.EstudoTabela_TotalP.getText().equals(""))){
                    totalND1 = totalHorizontal + Integer.parseInt(this.EstudoTabela_TotalP.getText());
                    this.EstudoTabela_TotalND1.setText(String.valueOf(totalND1));
                } else{
                    this.EstudoTabela_TotalND1.setText(String.valueOf(totalHorizontal));
                }
            } catch (NumberFormatException ex)   {
                JOptionPane.showMessageDialog(this.rootPane, "Por favor, insira um valor válido.");
                this.EstudoTabela_FNtext.setText("");
            }
        }
    }//GEN-LAST:event_EstudoTabela_FNtextFocusLost

    private void EstudoTabela_VNtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EstudoTabela_VNtextFocusLost
        int totalHorizontal = 0, totalVertical = 0, totalND1 = 0;
        if(!EstudoTabela_VNtext.getText().equals("")){
            try{
                if(!(EstudoTabela_FNtext.getText().equals(""))){
                    totalHorizontal = Integer.parseInt(this.EstudoTabela_VNtext.getText()) + Integer.parseInt(this.EstudoTabela_FNtext.getText());
                } else {
                    totalHorizontal = Integer.parseInt(this.EstudoTabela_VNtext.getText());
                }

                if(!(EstudoTabela_FPtext.getText().equals(""))){
                        totalVertical = Integer.parseInt(this.EstudoTabela_VNtext.getText()) + Integer.parseInt(this.EstudoTabela_FPtext.getText());
                    }else{
                        totalVertical = Integer.parseInt(this.EstudoTabela_VNtext.getText());
                    }
                this.EstudoTabela_TotalN.setText(String.valueOf(totalHorizontal));
                this.EstudoTabela_TotalND.setText(String.valueOf(totalVertical));
                
                 if(!(this.EstudoTabela_TotalP.getText().equals(""))){
                    totalND1 = totalHorizontal + Integer.parseInt(this.EstudoTabela_TotalP.getText());
                    this.EstudoTabela_TotalND1.setText(String.valueOf(totalND1));
                } else{
                    this.EstudoTabela_TotalND1.setText(String.valueOf(totalHorizontal));
                }
            } catch (NumberFormatException ex)   {
                JOptionPane.showMessageDialog(this.rootPane, "Por favor, insira um valor válido.");
                this.EstudoTabela_VNtext.setText("");
            }
        }
    }//GEN-LAST:event_EstudoTabela_VNtextFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstudoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstudoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstudoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstudoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstudoIndividual().setVisible(true);
            }
        });
    }
    
    private void confereIntervaloDeConfianca(double intervaloDeConfianca) throws ModuloLikelihoodException {
        if(intervaloDeConfianca < 0 || intervaloDeConfianca > 100){
            throw new ModuloLikelihoodException("Antes de cadastrar um novo estudo, por favor forneça um valor válido para o intervalo de confiança");
        } else {
             this.percentualIntervaloDeConfianca = intervaloDeConfianca;
        }
    }
    
    private MetanaliseEstudoIndividual efetuaMetanalise(EstudoIndividual estInd){
        try {
            Metanalise.calcula(estInd.getVp(), estInd.getFp(),  estInd.getVn(), estInd.getFn(), this.percentualIntervaloDeConfianca);
            return new MetanaliseEstudoIndividual(Metanalise.getPercentualIntervaloConfianca(), Metanalise.getSensibilidade(),
                    Metanalise.getEspecificidade(),  Metanalise.getLikelihoodPositiviva(),
                    Metanalise.getLikelihoodNegativa(), Metanalise.getErroPadrao_lkPositiva(),
                    Metanalise.getErroPadrao_lkNegativa(), Metanalise.getIntervaloConfianca_LKPositiva_zNegativo(),
                    Metanalise.getIntervaloConfianca_LKPositiva_zPositivo(),
                    Metanalise.getIntervaloConfianca_LKNegativa_zNegativo(),
                    Metanalise.getIntervaloConfianca_LKNegativa_zPositivo(),
                    Metanalise.getPeso_MH_LKPositiva(), Metanalise.getPeso_MH_LKNegativa());
        } catch (ModuloLikelihoodException ex) {
            JOptionPane.showMessageDialog(this.rootPane, ex.getMessage());
            return null;
        }
    }
    
    private void atualizaDados_Tela(String textoBotao){
        this.EstudoID_text.setEditable(true);
        this.EstudoDesc_textarea.setEditable(false);
        this.EstudoDesc_textarea.setBackground(getBackground());
        this.EstudoTabela_VPtext.setEditable(false);
        this.EstudoTabela_FPtext.setEditable(false);
        this.EstudoTabela_FNtext.setEditable(false);
        this.EstudoTabela_VNtext.setEditable(false);
    }
    
    private void atualizaDados_Tela(ArrayList<EstudoIndividual> listaDados){
        this.estInd = listaDados.get(0);
        
        this.EstudoID_text.setText(estInd.getId().toString());
        this.EstudoID_text.setEditable(false);
        this.EstudoTitulo_text.setText(estInd.getTitulo());
        this.EstudoDesc_textarea.setText(estInd.getDescricao());
        this.EstudoDesc_textarea.setEditable(true);
        this.EstudoDesc_textarea.setBackground(Color.WHITE);
        this.EstudoTabela_VPtext.setText(String.valueOf(estInd.getVp()));
        this.EstudoTabela_VPtext.setEditable(true);
        this.EstudoTabela_FPtext.setText(String.valueOf(estInd.getFp()));
        this.EstudoTabela_FPtext.setEditable(true);
        this.EstudoTabela_VNtext.setText(String.valueOf(estInd.getVn()));
        this.EstudoTabela_VNtext.setEditable(true);
        this.EstudoTabela_FNtext.setText(String.valueOf(estInd.getFn()));
        this.EstudoTabela_FNtext.setEditable(true);
        this.EstudoTabela_FNtextFocusLost(null);
        this.EstudoTabela_VNtextFocusLost(null);
        this.EstudoTabela_VPtextFocusLost(null);
        this.EstudoTabela_FPtextFocusLost(null);
        this.EstudoButton_button.setText("Alterar");
    }
    
    private void atualizaDados_Tela(){
        this.EstudoID_text.setText("");
        this.EstudoID_text.setEditable(false);
        this.EstudoTitulo_text.setText("");
        this.EstudoDesc_textarea.setText("");
        this.EstudoTabela_VPtext.setText("");
        this.EstudoTabela_FPtext.setText("");
        this.EstudoTabela_VNtext.setText("");
        this.EstudoTabela_FNtext.setText("");
        this.EstudoTabela_TotalD.setText("");
        this.EstudoTabela_TotalN.setText("");
        this.EstudoTabela_TotalND.setText("");
        this.EstudoTabela_TotalP.setText("");
        this.EstudoTabela_TotalND1.setText("");
        
        this.EstudoButton_button.setText("Cadastrar");
    }
    
    public double getPercentualIntervaloDeConfianca() {
        return percentualIntervaloDeConfianca;
    }

    public void setPercentualIntervaloDeConfianca(double percentualIntervaloDeConfianca) {
        this.percentualIntervaloDeConfianca = percentualIntervaloDeConfianca;
    }

    public EstudoIndividual getEstInd() {
        return estInd;
    }

    public void setEstInd(EstudoIndividual estInd) {
        this.estInd = estInd;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EstudoButton_button;
    private javax.swing.JLabel EstudoDesc_label;
    private javax.swing.JTextArea EstudoDesc_textarea;
    private javax.swing.JLabel EstudoID_label;
    private javax.swing.JTextField EstudoID_text;
    private javax.swing.JTextField EstudoTabela_FNtext;
    private javax.swing.JTextField EstudoTabela_FPtext;
    private javax.swing.JTextField EstudoTabela_TotalD;
    private javax.swing.JTextField EstudoTabela_TotalN;
    private javax.swing.JTextField EstudoTabela_TotalND;
    private javax.swing.JTextField EstudoTabela_TotalND1;
    private javax.swing.JTextField EstudoTabela_TotalP;
    private javax.swing.JTextField EstudoTabela_VNtext;
    private javax.swing.JTextField EstudoTabela_VPtext;
    private javax.swing.JLabel EstudoTabela_label1;
    private javax.swing.JLabel EstudoTabela_label2;
    private javax.swing.JLabel EstudoTabela_label3;
    private javax.swing.JLabel EstudoTabela_label4;
    private javax.swing.JLabel EstudoTabela_label5;
    private javax.swing.JLabel EstudoTabela_label6;
    private javax.swing.JLabel EstudoTabela_label7;
    private javax.swing.JLabel EstudoTabela_label8;
    private javax.swing.JTable EstudoTabela_table1;
    private javax.swing.JLabel EstudoTitulo_label;
    private javax.swing.JTextField EstudoTitulo_text;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
