/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mapeamento.EstudoIndividual;
import mapeamento.MetanaliseEstudoIndividual;
import moduloLikelihoodException.ModuloLikelihoodException;

/**
 *
 * @author allan
 */
public class TelaMetanaliseEstudoIndividual extends javax.swing.JFrame {
    
    private Vector<String> tableHeaders = new Vector<String>();
    private Vector<Object> oneRow = null;
    private Vector tableData = new Vector();

    /**
     * Creates new form TelaMetanaliseEstudoIndividual
     */
    public TelaMetanaliseEstudoIndividual() {
        inicializaTela();
        initComponents();
    }
    
    public TelaMetanaliseEstudoIndividual(int estInd_id) {
        inicializaTela();
        initComponents();
        
        this.MetEstInd_TabelaListagem_table.changeSelection((estInd_id-1), 0, true, false);
        this.MetEstInd_TabelaListagem_tableMouseClicked(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EstudoTitulo_label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MetEstInd_TabelaListagem_table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        MetEstInd_PercentualIntConf_label = new javax.swing.JLabel();
        MetEstInd_PercentualIntConf_text = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        MetEstInd_LKNegativa_label = new javax.swing.JLabel();
        MetEstInd_LKPositiva_label = new javax.swing.JLabel();
        MetEstInd_Especificidade_label = new javax.swing.JLabel();
        MetEstInd_Sensibilidade_label = new javax.swing.JLabel();
        MetEstInd_Sensibilidade_text = new javax.swing.JTextField();
        MetEstInd_Especificidade_text = new javax.swing.JTextField();
        MetEstInd_LKPositiva_text = new javax.swing.JTextField();
        MetEstInd_LKNegativa_text = new javax.swing.JTextField();
        MetEstInd_ErroPadraoLKPositiva_label = new javax.swing.JLabel();
        MetEstInd_ErroPadraoLKPositiva_text = new javax.swing.JTextField();
        MetEstInd_ErroPadraoLKNegativa_label = new javax.swing.JLabel();
        MetEstInd_ErroPadraoLKNegativa_text = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        MetEstInd_IntConfInfLKPositiva_text = new javax.swing.JTextField();
        MetEstInd_IntConfInfLKPositiva_label = new javax.swing.JLabel();
        MetEstInd_IntConfSupLKPositiva_label = new javax.swing.JLabel();
        MetEstInd_IntConfSupLKPositiva_text = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        MetEstInd_IntConfInfLKNegativa_label = new javax.swing.JLabel();
        MetEstInd_IntConfInfLKNegativa_text = new javax.swing.JTextField();
        MetEstInd_IntConfSupLKNegativa_text = new javax.swing.JTextField();
        MetEstInd_IntConfSupLKNegativa_label = new javax.swing.JLabel();
        MetEstInd_PesoMHLKPositiva_label = new javax.swing.JLabel();
        MetEstInd_PesoMHLKPositiva_text = new javax.swing.JTextField();
        MetEstInd_PesoMHLKNegativa_label = new javax.swing.JLabel();
        MetEstInd_PesoMHLKNegativa_text = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Metanálise Estudo Individual");
        setResizable(false);

        EstudoTitulo_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        MetEstInd_TabelaListagem_table.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MetEstInd_TabelaListagem_table.setModel(new DefaultTableModel(tableData, tableHeaders));
        MetEstInd_TabelaListagem_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MetEstInd_TabelaListagem_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(MetEstInd_TabelaListagem_table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        MetEstInd_PercentualIntConf_label.setText("Percentual Intervalo de Confiança");

        MetEstInd_PercentualIntConf_text.setEditable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        MetEstInd_LKNegativa_label.setText("Likelihood Negativa");

        MetEstInd_LKPositiva_label.setText("Likelihood Positiva");

        MetEstInd_Especificidade_label.setText("Especificidade");

        MetEstInd_Sensibilidade_label.setText("Sensibilidade");

        MetEstInd_Sensibilidade_text.setEditable(false);

        MetEstInd_Especificidade_text.setEditable(false);

        MetEstInd_LKPositiva_text.setEditable(false);

        MetEstInd_LKNegativa_text.setEditable(false);

        MetEstInd_ErroPadraoLKPositiva_label.setText("Erro Padrão");

        MetEstInd_ErroPadraoLKPositiva_text.setEditable(false);

        MetEstInd_ErroPadraoLKNegativa_label.setText("Erro Padrão");

        MetEstInd_ErroPadraoLKNegativa_text.setEditable(false);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Intervalos de confiança"));

        MetEstInd_IntConfInfLKPositiva_text.setEditable(false);

        MetEstInd_IntConfInfLKPositiva_label.setText("Inferior");

        MetEstInd_IntConfSupLKPositiva_label.setText("Superior");

        MetEstInd_IntConfSupLKPositiva_text.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(MetEstInd_IntConfInfLKPositiva_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MetEstInd_IntConfInfLKPositiva_text, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(MetEstInd_IntConfSupLKPositiva_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MetEstInd_IntConfSupLKPositiva_text, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MetEstInd_IntConfInfLKPositiva_label)
                    .addComponent(MetEstInd_IntConfInfLKPositiva_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MetEstInd_IntConfSupLKPositiva_label)
                    .addComponent(MetEstInd_IntConfSupLKPositiva_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Intervalos de Confiança"));

        MetEstInd_IntConfInfLKNegativa_label.setText("Inferior");

        MetEstInd_IntConfInfLKNegativa_text.setEditable(false);

        MetEstInd_IntConfSupLKNegativa_text.setEditable(false);

        MetEstInd_IntConfSupLKNegativa_label.setText("Superior");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(MetEstInd_IntConfSupLKNegativa_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MetEstInd_IntConfSupLKNegativa_text, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(MetEstInd_IntConfInfLKNegativa_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MetEstInd_IntConfInfLKNegativa_text, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MetEstInd_IntConfInfLKNegativa_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MetEstInd_IntConfInfLKNegativa_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MetEstInd_IntConfSupLKNegativa_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MetEstInd_IntConfSupLKNegativa_label))
                .addGap(6, 6, 6))
        );

        MetEstInd_PesoMHLKPositiva_label.setText("Peso Mantel-Hansel");

        MetEstInd_PesoMHLKPositiva_text.setEditable(false);

        MetEstInd_PesoMHLKNegativa_label.setText("Peso Mantel-Hansel");

        MetEstInd_PesoMHLKNegativa_text.setEditable(false);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MetEstInd_LKPositiva_label)
                                    .addComponent(MetEstInd_ErroPadraoLKPositiva_label))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MetEstInd_ErroPadraoLKPositiva_text, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                    .addComponent(MetEstInd_LKPositiva_text)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(MetEstInd_PesoMHLKPositiva_label)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MetEstInd_PesoMHLKPositiva_text, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(19, 19, 19)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MetEstInd_LKNegativa_label)
                                    .addComponent(MetEstInd_ErroPadraoLKNegativa_label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MetEstInd_LKNegativa_text, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                    .addComponent(MetEstInd_ErroPadraoLKNegativa_text))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(MetEstInd_PesoMHLKNegativa_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MetEstInd_PesoMHLKNegativa_text, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(MetEstInd_Sensibilidade_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MetEstInd_Sensibilidade_text, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MetEstInd_Especificidade_label)
                        .addGap(41, 41, 41)
                        .addComponent(MetEstInd_Especificidade_text, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jSeparator1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MetEstInd_Sensibilidade_label)
                            .addComponent(MetEstInd_Sensibilidade_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MetEstInd_Especificidade_label)
                            .addComponent(MetEstInd_Especificidade_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MetEstInd_LKPositiva_label)
                            .addComponent(MetEstInd_LKPositiva_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MetEstInd_ErroPadraoLKPositiva_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MetEstInd_ErroPadraoLKPositiva_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MetEstInd_PesoMHLKPositiva_label)
                            .addComponent(MetEstInd_PesoMHLKPositiva_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MetEstInd_LKNegativa_label)
                            .addComponent(MetEstInd_LKNegativa_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MetEstInd_ErroPadraoLKNegativa_label)
                            .addComponent(MetEstInd_ErroPadraoLKNegativa_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MetEstInd_PesoMHLKNegativa_label)
                            .addComponent(MetEstInd_PesoMHLKNegativa_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(MetEstInd_PercentualIntConf_label)
                        .addGap(54, 54, 54)
                        .addComponent(MetEstInd_PercentualIntConf_text, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MetEstInd_PercentualIntConf_label)
                    .addComponent(MetEstInd_PercentualIntConf_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(293, 293, 293))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(EstudoTitulo_label)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EstudoTitulo_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MetEstInd_TabelaListagem_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MetEstInd_TabelaListagem_tableMouseClicked
        this.limpaTela();
        ArrayList queryResults = null;
        try {
            queryResults = persistencia.CRUD.executaConsulta(String.valueOf(this.MetEstInd_TabelaListagem_table.getValueAt(this.MetEstInd_TabelaListagem_table.getSelectedRow(), 0)), null);
            EstudoIndividual estInd = null;
            if (!queryResults.isEmpty()) estInd = (EstudoIndividual) queryResults.get(0); this.atualizaTela(estInd.getMetanaliseEstudoIndividual(), estInd.getTitulo());
            
           // int estInd_titulo_labelLocation = 1219/this.EstudoTitulo_label.getSize().width;
           // this.EstudoTitulo_label.setLocation(1, 1);
        } catch (ModuloLikelihoodException ex) {
            JOptionPane.showMessageDialog(this.rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_MetEstInd_TabelaListagem_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMetanaliseEstudoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMetanaliseEstudoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMetanaliseEstudoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMetanaliseEstudoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMetanaliseEstudoIndividual().setVisible(true);
            }
        });
    }
    
    private void inicializaTela(){
        this.tableHeaders.add("ID"); 
        this.tableHeaders.add("Título");
        this.tableHeaders.add("Descrição");
        
        for(Object obj : persistencia.CRUD.executaConsulta()){
            EstudoIndividual estInd = (EstudoIndividual) obj;
            this.oneRow = new Vector<Object>();
            this.oneRow.add(estInd.getId());
            this.oneRow.add(estInd.getTitulo());
            this.oneRow.add(estInd.getDescricao());
            this.tableData.add(oneRow);
        }
    }
    
    private void atualizaTela(MetanaliseEstudoIndividual metEstInd, String estInd_titulo){
        this.EstudoTitulo_label.setText(estInd_titulo);
        
        if(!(metEstInd == null)){
            this.MetEstInd_PercentualIntConf_text.setText(String.valueOf(metEstInd.getPercentualIntervaloConfianca()));
            this.MetEstInd_Sensibilidade_text.setText(String.valueOf(metEstInd.getSensibilidade()));
            this.MetEstInd_Especificidade_text.setText(String.valueOf(metEstInd.getEspecificidade()));
            this.MetEstInd_LKPositiva_text.setText(String.valueOf(metEstInd.getLikelihoodPositiviva()));
            this.MetEstInd_LKNegativa_text.setText(String.valueOf(metEstInd.getLikelihoodNegativa()));
            this.MetEstInd_ErroPadraoLKPositiva_text.setText(String.valueOf(metEstInd.getErroPadraoLkPositiva()));
            this.MetEstInd_ErroPadraoLKNegativa_text.setText(String.valueOf(metEstInd.getErroPadraoLkNegativa()));
            this.MetEstInd_IntConfSupLKPositiva_text.setText(String.valueOf(metEstInd.getIntervaloConfiancaLkpositivoZPositivo()));
            this.MetEstInd_IntConfInfLKPositiva_text.setText(String.valueOf(metEstInd.getIntervaloConfiancaLkpositivaZNegativo()));
            this.MetEstInd_IntConfSupLKNegativa_text.setText(String.valueOf(metEstInd.getIntervaloConfiancaLknegativaZPositivo()));
            this.MetEstInd_IntConfInfLKNegativa_text.setText(String.valueOf(metEstInd.getIntervaloConfiancaLknegativaZPositivo()));
            this.MetEstInd_PesoMHLKPositiva_text.setText(String.valueOf(metEstInd.getPesoMhLkpositiva()));
            this.MetEstInd_PesoMHLKNegativa_text.setText(String.valueOf(metEstInd.getPesoMhLknegativa()));
        }
    }
    
    private void limpaTela(){
        this.MetEstInd_PercentualIntConf_text.setText("");
            this.MetEstInd_Sensibilidade_text.setText("");
            this.MetEstInd_Sensibilidade_text.setText("");
            this.MetEstInd_Especificidade_text.setText("");
            this.MetEstInd_LKPositiva_text.setText("");
            this.MetEstInd_LKNegativa_text.setText("");
            this.MetEstInd_ErroPadraoLKPositiva_text.setText("");
            this.MetEstInd_ErroPadraoLKNegativa_text.setText("");
            this.MetEstInd_IntConfSupLKPositiva_text.setText("");
            this.MetEstInd_IntConfInfLKPositiva_text.setText("");
            this.MetEstInd_IntConfSupLKNegativa_text.setText("");
            this.MetEstInd_IntConfInfLKNegativa_text.setText("");
            this.MetEstInd_PesoMHLKPositiva_text.setText("");
            this.MetEstInd_PesoMHLKNegativa_text.setText("");
    }
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EstudoTitulo_label;
    private javax.swing.JLabel MetEstInd_ErroPadraoLKNegativa_label;
    private javax.swing.JTextField MetEstInd_ErroPadraoLKNegativa_text;
    private javax.swing.JLabel MetEstInd_ErroPadraoLKPositiva_label;
    private javax.swing.JTextField MetEstInd_ErroPadraoLKPositiva_text;
    private javax.swing.JLabel MetEstInd_Especificidade_label;
    private javax.swing.JTextField MetEstInd_Especificidade_text;
    private javax.swing.JLabel MetEstInd_IntConfInfLKNegativa_label;
    private javax.swing.JTextField MetEstInd_IntConfInfLKNegativa_text;
    private javax.swing.JLabel MetEstInd_IntConfInfLKPositiva_label;
    private javax.swing.JTextField MetEstInd_IntConfInfLKPositiva_text;
    private javax.swing.JLabel MetEstInd_IntConfSupLKNegativa_label;
    private javax.swing.JTextField MetEstInd_IntConfSupLKNegativa_text;
    private javax.swing.JLabel MetEstInd_IntConfSupLKPositiva_label;
    private javax.swing.JTextField MetEstInd_IntConfSupLKPositiva_text;
    private javax.swing.JLabel MetEstInd_LKNegativa_label;
    private javax.swing.JTextField MetEstInd_LKNegativa_text;
    private javax.swing.JLabel MetEstInd_LKPositiva_label;
    private javax.swing.JTextField MetEstInd_LKPositiva_text;
    private javax.swing.JLabel MetEstInd_PercentualIntConf_label;
    private javax.swing.JTextField MetEstInd_PercentualIntConf_text;
    private javax.swing.JLabel MetEstInd_PesoMHLKNegativa_label;
    private javax.swing.JTextField MetEstInd_PesoMHLKNegativa_text;
    private javax.swing.JLabel MetEstInd_PesoMHLKPositiva_label;
    private javax.swing.JTextField MetEstInd_PesoMHLKPositiva_text;
    private javax.swing.JLabel MetEstInd_Sensibilidade_label;
    private javax.swing.JTextField MetEstInd_Sensibilidade_text;
    private javax.swing.JTable MetEstInd_TabelaListagem_table;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
