/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import moduloLikelihoodException.ModuloLikelihoodException;

/**
 *
 * @author allan
 */
public class TelaHome extends javax.swing.JFrame {

    private double intervaloDeConfianca;
    
    /**
     * Creates new form TelaHome
     */
    public TelaHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IntervaloDeConfianca_label = new javax.swing.JLabel();
        IntervaloDeConfianca_text = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        EstudoMenu = new javax.swing.JMenu();
        EstudoIndividual_Cadastrar = new javax.swing.JMenuItem();
        EstudoIndividual_Consultar = new javax.swing.JMenuItem();
        EstudoIndividual_Excluir = new javax.swing.JMenuItem();
        EstudoGlobalMenu = new javax.swing.JMenu();
        EstudoGlobal_Cadastrar = new javax.swing.JMenuItem();
        EstudoGlobal_Listagem = new javax.swing.JMenuItem();
        AjudaMenu = new javax.swing.JMenu();
        SobreAjuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SHELL PEARSON | Módulo Likelihood ");
        setIconImage(new ImageIcon("src/conteudo/icone.jpg").getImage());
        setName("TelaHome"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        IntervaloDeConfianca_label.setText("Intervalo de Confiança");

        IntervaloDeConfianca_text.setForeground(new java.awt.Color(153, 153, 153));
        IntervaloDeConfianca_text.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        IntervaloDeConfianca_text.setText("95");
        IntervaloDeConfianca_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IntervaloDeConfianca_textKeyTyped(evt);
            }
        });

        jLabel1.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IntervaloDeConfianca_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(IntervaloDeConfianca_text, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IntervaloDeConfianca_label)
                    .addComponent(IntervaloDeConfianca_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conteudo/icone.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(86, 86, 86))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(83, 83, 83))
        );

        EstudoMenu.setText("Estudos Individuais");

        EstudoIndividual_Cadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        EstudoIndividual_Cadastrar.setText("Cadastrar");
        EstudoIndividual_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudoIndividual_CadastrarActionPerformed(evt);
            }
        });
        EstudoMenu.add(EstudoIndividual_Cadastrar);

        EstudoIndividual_Consultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        EstudoIndividual_Consultar.setText("Consultar");
        EstudoIndividual_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudoIndividual_ConsultarActionPerformed(evt);
            }
        });
        EstudoMenu.add(EstudoIndividual_Consultar);

        EstudoIndividual_Excluir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        EstudoIndividual_Excluir.setText("Listagem");
        EstudoIndividual_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudoIndividual_ExcluirActionPerformed(evt);
            }
        });
        EstudoMenu.add(EstudoIndividual_Excluir);

        jMenuBar1.add(EstudoMenu);

        EstudoGlobalMenu.setText("Estudos Globais");

        EstudoGlobal_Cadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        EstudoGlobal_Cadastrar.setText("Cadastrar");
        EstudoGlobal_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudoGlobal_CadastrarActionPerformed(evt);
            }
        });
        EstudoGlobalMenu.add(EstudoGlobal_Cadastrar);

        EstudoGlobal_Listagem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        EstudoGlobal_Listagem.setText("Listagem");
        EstudoGlobal_Listagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudoGlobal_ListagemActionPerformed(evt);
            }
        });
        EstudoGlobalMenu.add(EstudoGlobal_Listagem);

        jMenuBar1.add(EstudoGlobalMenu);

        AjudaMenu.setText("Ajuda");

        SobreAjuda.setText("Sobre");
        SobreAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreAjudaActionPerformed(evt);
            }
        });
        AjudaMenu.add(SobreAjuda);

        jMenuBar1.add(AjudaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(471, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EstudoIndividual_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudoIndividual_CadastrarActionPerformed
        
        try{
            this.intervaloDeConfianca = Double.parseDouble(this.IntervaloDeConfianca_text.getText()); 
            new TelaEstudoIndividual("Cadastrar", this.intervaloDeConfianca).setVisible(true);
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this.rootPane, "Antes de cadastrar um novo estudo, por favor forneça um valor válido para o intervalo de confiança");
        } catch (ModuloLikelihoodException ex){
            JOptionPane.showMessageDialog(this.rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_EstudoIndividual_CadastrarActionPerformed

    private void EstudoIndividual_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudoIndividual_ConsultarActionPerformed
        try{        
            this.intervaloDeConfianca = Double.parseDouble(IntervaloDeConfianca_text.getText()); 
            new TelaEstudoIndividual("Consultar", this.intervaloDeConfianca).setVisible(true);
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this.rootPane, "Antes de cadastrar um novo estudo, por favor forneça um valor válido para o intervalo de confiança");
        } catch (ModuloLikelihoodException ex){
            JOptionPane.showMessageDialog(this.rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_EstudoIndividual_ConsultarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ModuloLikelihood.fechaSessaoHibernate();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.IntervaloDeConfianca_text.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void IntervaloDeConfianca_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IntervaloDeConfianca_textKeyTyped
        this.IntervaloDeConfianca_text.setForeground(Color.BLACK);
    }//GEN-LAST:event_IntervaloDeConfianca_textKeyTyped

    private void SobreAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreAjudaActionPerformed
        new gui.TelaSobre().setVisible(true);
    }//GEN-LAST:event_SobreAjudaActionPerformed

    private void EstudoIndividual_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudoIndividual_ExcluirActionPerformed
        new gui.TelaListagemEstudosIndividuais(this.intervaloDeConfianca).setVisible(true);
    }//GEN-LAST:event_EstudoIndividual_ExcluirActionPerformed

    private void EstudoGlobal_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudoGlobal_CadastrarActionPerformed
        new gui.TelaEstudoGlobal().setVisible(true);
    }//GEN-LAST:event_EstudoGlobal_CadastrarActionPerformed

    private void EstudoGlobal_ListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudoGlobal_ListagemActionPerformed
       new gui.TelaListagemEstudosGlobais().setVisible(true);
    }//GEN-LAST:event_EstudoGlobal_ListagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHome().setVisible(true);
            }
        });
    }
    
    public double getIntervaloDeConfianca() {
        return this.intervaloDeConfianca;
    }

    public void setIntervaloDeConfianca(double intervaloDeConfianca) {
        this.intervaloDeConfianca = intervaloDeConfianca;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AjudaMenu;
    private javax.swing.JMenu EstudoGlobalMenu;
    private javax.swing.JMenuItem EstudoGlobal_Cadastrar;
    private javax.swing.JMenuItem EstudoGlobal_Listagem;
    private javax.swing.JMenuItem EstudoIndividual_Cadastrar;
    private javax.swing.JMenuItem EstudoIndividual_Consultar;
    private javax.swing.JMenuItem EstudoIndividual_Excluir;
    private javax.swing.JMenu EstudoMenu;
    private javax.swing.JLabel IntervaloDeConfianca_label;
    private javax.swing.JTextField IntervaloDeConfianca_text;
    private javax.swing.JMenuItem SobreAjuda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
