/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mapeamento.EstudoIndividual;
import moduloLikelihoodException.ModuloLikelihoodException;

/**
 *
 * @author allan
 */
public class TelaListagemEstudosIndividuais extends javax.swing.JFrame {

    private Vector<String> tableHeaders = new Vector<String>();
    private Vector<Object> oneRow = null;
    private Vector tableData = new Vector();
    
    /**
     * Creates new form TelaListagemEstudosIndividuais
     */
    public TelaListagemEstudosIndividuais() {
        inicializaTela();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listagemEstInd_tabela = new javax.swing.JTable();
        listagemEstInd_deletar_button = new javax.swing.JButton();
        listagemEstInd_alterarDados_button = new javax.swing.JButton();
        listagemEstInd_removerEstGlob_button = new javax.swing.JButton();
        listagemEstInd_abrirMet_button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listagem Estudos Individuais");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        listagemEstInd_tabela.setModel(new javax.swing.table.DefaultTableModel(tableData, tableHeaders)
        );
        this.listagemEstInd_tabela.setSelectionMode(NORMAL);
        jScrollPane1.setViewportView(listagemEstInd_tabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listagemEstInd_deletar_button.setText("Deletar");

        listagemEstInd_alterarDados_button.setText("Alterar dados");
        listagemEstInd_alterarDados_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listagemEstInd_alterarDados_buttonActionPerformed(evt);
            }
        });

        listagemEstInd_removerEstGlob_button.setText("Remover de Estudo Global");
        listagemEstInd_removerEstGlob_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listagemEstInd_removerEstGlob_buttonActionPerformed(evt);
            }
        });

        listagemEstInd_abrirMet_button.setText("Abrir Metanálise");
        listagemEstInd_abrirMet_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listagemEstInd_abrirMet_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listagemEstInd_removerEstGlob_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listagemEstInd_alterarDados_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listagemEstInd_abrirMet_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listagemEstInd_deletar_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(listagemEstInd_abrirMet_button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listagemEstInd_alterarDados_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(listagemEstInd_removerEstGlob_button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listagemEstInd_deletar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listagemEstInd_abrirMet_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listagemEstInd_abrirMet_buttonActionPerformed
       if(this.listagemEstInd_tabela.getSelectedRow() >= 0){
           new gui.TelaMetanaliseEstudoIndividual(this.listagemEstInd_tabela.getSelectedRow()+1).setVisible(true);
       }
    }//GEN-LAST:event_listagemEstInd_abrirMet_buttonActionPerformed

    private void listagemEstInd_alterarDados_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listagemEstInd_alterarDados_buttonActionPerformed
        if(this.listagemEstInd_tabela.getSelectedRow() >= 0){
            ArrayList queryResults = null;
            try {
                queryResults = persistencia.CRUD.executaConsulta(String.valueOf(this.listagemEstInd_tabela.getSelectedRow()+1), null);
            } catch (ModuloLikelihoodException ex) {
                JOptionPane.showMessageDialog(this.rootPane, ex.getMessage());
            }
            new gui.TelaEstudoIndividual(queryResults).setVisible(true);
        }
    }//GEN-LAST:event_listagemEstInd_alterarDados_buttonActionPerformed

    private void listagemEstInd_removerEstGlob_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listagemEstInd_removerEstGlob_buttonActionPerformed
        
    }//GEN-LAST:event_listagemEstInd_removerEstGlob_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListagemEstudosIndividuais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListagemEstudosIndividuais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListagemEstudosIndividuais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListagemEstudosIndividuais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListagemEstudosIndividuais().setVisible(true);
            }
        });
    }

    private void inicializaTela(){
        this.tableHeaders.add("ID"); 
        this.tableHeaders.add("Título");
        this.tableHeaders.add("Descrição");
        this.tableHeaders.add("VP");
        this.tableHeaders.add("FP");
        this.tableHeaders.add("VN");
        this.tableHeaders.add("FN");
        
        for(Object obj : persistencia.CRUD.executaConsulta()){
            EstudoIndividual estInd = (EstudoIndividual) obj;
            this.oneRow = new Vector<Object>();
            this.oneRow.add(estInd.getId());
            this.oneRow.add(estInd.getTitulo());
            this.oneRow.add(estInd.getDescricao());
            this.oneRow.add(estInd.getVp());
            this.oneRow.add(estInd.getFp());
            this.oneRow.add(estInd.getVn());
            this.oneRow.add(estInd.getFn());
            this.tableData.add(oneRow);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton listagemEstInd_abrirMet_button;
    private javax.swing.JButton listagemEstInd_alterarDados_button;
    private javax.swing.JButton listagemEstInd_deletar_button;
    private javax.swing.JButton listagemEstInd_removerEstGlob_button;
    private javax.swing.JTable listagemEstInd_tabela;
    // End of variables declaration//GEN-END:variables
}
