package controle;
// Generated Sep 18, 2015 3:44:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estudoglobal generated by hbm2java
 */
public class Estudoglobal  implements java.io.Serializable {


     private Integer id;
     private double lkPositivo;
     private double lkNegativo;
     private double erroPadrao;
     private double intervaloConfSup;
     private double intervaloConfInf;
     private Set estudoindividuals = new HashSet(0);

    public Estudoglobal() {
    }

	
    public Estudoglobal(double lkPositivo, double lkNegativo, double erroPadrao, double intervaloConfSup, double intervaloConfInf) {
        this.lkPositivo = lkPositivo;
        this.lkNegativo = lkNegativo;
        this.erroPadrao = erroPadrao;
        this.intervaloConfSup = intervaloConfSup;
        this.intervaloConfInf = intervaloConfInf;
    }
    public Estudoglobal(double lkPositivo, double lkNegativo, double erroPadrao, double intervaloConfSup, double intervaloConfInf, Set estudoindividuals) {
       this.lkPositivo = lkPositivo;
       this.lkNegativo = lkNegativo;
       this.erroPadrao = erroPadrao;
       this.intervaloConfSup = intervaloConfSup;
       this.intervaloConfInf = intervaloConfInf;
       this.estudoindividuals = estudoindividuals;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public double getLkPositivo() {
        return this.lkPositivo;
    }
    
    public void setLkPositivo(double lkPositivo) {
        this.lkPositivo = lkPositivo;
    }
    public double getLkNegativo() {
        return this.lkNegativo;
    }
    
    public void setLkNegativo(double lkNegativo) {
        this.lkNegativo = lkNegativo;
    }
    public double getErroPadrao() {
        return this.erroPadrao;
    }
    
    public void setErroPadrao(double erroPadrao) {
        this.erroPadrao = erroPadrao;
    }
    public double getIntervaloConfSup() {
        return this.intervaloConfSup;
    }
    
    public void setIntervaloConfSup(double intervaloConfSup) {
        this.intervaloConfSup = intervaloConfSup;
    }
    public double getIntervaloConfInf() {
        return this.intervaloConfInf;
    }
    
    public void setIntervaloConfInf(double intervaloConfInf) {
        this.intervaloConfInf = intervaloConfInf;
    }
    public Set getEstudoindividuals() {
        return this.estudoindividuals;
    }
    
    public void setEstudoindividuals(Set estudoindividuals) {
        this.estudoindividuals = estudoindividuals;
    }




}


