package controle;
// Generated Sep 18, 2015 3:44:32 PM by Hibernate Tools 4.3.1



/**
 * Metanaliseestudoindividual generated by hbm2java
 */
public class Metanaliseestudoindividual  implements java.io.Serializable {


     private Integer id;
     private Estudoindividual estudoindividual;
     private double lkPositivo;
     private double lkNegativo;
     private double erroPadrao;
     private double intervaloConfSup;
     private double intervaloConfInf;

    public Metanaliseestudoindividual() {
    }

	
    public Metanaliseestudoindividual(double lkPositivo, double lkNegativo, double erroPadrao, double intervaloConfSup, double intervaloConfInf) {
        this.lkPositivo = lkPositivo;
        this.lkNegativo = lkNegativo;
        this.erroPadrao = erroPadrao;
        this.intervaloConfSup = intervaloConfSup;
        this.intervaloConfInf = intervaloConfInf;
    }
    public Metanaliseestudoindividual(Estudoindividual estudoindividual, double lkPositivo, double lkNegativo, double erroPadrao, double intervaloConfSup, double intervaloConfInf) {
       this.estudoindividual = estudoindividual;
       this.lkPositivo = lkPositivo;
       this.lkNegativo = lkNegativo;
       this.erroPadrao = erroPadrao;
       this.intervaloConfSup = intervaloConfSup;
       this.intervaloConfInf = intervaloConfInf;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Estudoindividual getEstudoindividual() {
        return this.estudoindividual;
    }
    
    public void setEstudoindividual(Estudoindividual estudoindividual) {
        this.estudoindividual = estudoindividual;
    }
    public double getLkPositivo() {
        return this.lkPositivo;
    }
    
    public void setLkPositivo(double lkPositivo) {
        this.lkPositivo = lkPositivo;
    }
    public double getLkNegativo() {
        return this.lkNegativo;
    }
    
    public void setLkNegativo(double lkNegativo) {
        this.lkNegativo = lkNegativo;
    }
    public double getErroPadrao() {
        return this.erroPadrao;
    }
    
    public void setErroPadrao(double erroPadrao) {
        this.erroPadrao = erroPadrao;
    }
    public double getIntervaloConfSup() {
        return this.intervaloConfSup;
    }
    
    public void setIntervaloConfSup(double intervaloConfSup) {
        this.intervaloConfSup = intervaloConfSup;
    }
    public double getIntervaloConfInf() {
        return this.intervaloConfInf;
    }
    
    public void setIntervaloConfInf(double intervaloConfInf) {
        this.intervaloConfInf = intervaloConfInf;
    }




}


